### ISSUE TITLE
Multi-language subtitle support

### ISSUE THREAD

**Issue by atlantis451** [teixeira0x/SubTypo#22]
You can include several languages in one .srt file.
It supports choosing font colors for each language
- Multi-language subtitle https://raw.githubusercontent.com/Pantyhose-X/Pantyhose-X/main/subtitle.srt

![image](https://github.com/user-attachments/assets/2c45500d-ffef-4a4c-924b-125d05cf18b3)

**Comment by teixeira0x** [comment]
I didn't know, thanks for the information
