### ISSUE TITLE
NPE on saving srt file.

### ISSUE THREAD

**Issue by Anonymous2716** [teixeira0x/SubTypo#29]
attempt to invoke Virtual method java.io.File.getAbsolutePath() on a null object reference.

 When I click save button on the SAF app.  Shows this dialog and creates an empty file. 

Android 14. Let me know if you need more info.

**Comment by teixeira0x** [comment]
Which version are you using, the latest version or the workflow version?

**Comment by teixeira0x** [comment]
I managed to reproduce it, I'm fixing it as soon as possible!

**Comment by Anonymous2716** [comment]
I was using latest from izzyOnDroids repository, now it is fixed. Thanks.

**Comment by teixeira0x** [comment]
> Eu estava usando o mais recente do repositório izzyOnDroids naquela época, agora está corrigido. Obrigado.

You're welcome! I appreciate you using the app
